FROM --platform=linux/amd64 ubuntu:22.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y git freeglut3-dev python3-dev python-is-python3

COPY . /repo
WORKDIR /repo/build
RUN cmake ..
RUN make -j8
RUN make examples
RUN rm /repo/examples/cermet.ics
